apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ci-cd
  labels: { app: flask-ci-cd }
spec:
  replicas: 1
  selector: { matchLabels: { app: flask-ci-cd } }
  template:
    metadata: { labels: { app: flask-ci-cd } }
    spec:
      containers:
      - name: flask
        image: sadikmert/flask-ci-cd:latest   # <-- BURAYI KENDİ ADINLA DEĞİŞTİR
        imagePullPolicy: Always
        ports: [{ containerPort: 5000 }]
        readinessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 10